# Bonus task

version: "3"
services:
  web:
    image: nova-app
    build: .
    ports:
      - "8080:80"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"