global:
  scrape_interval: 30s  # Check the site every 30 seconds

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Expect HTTP 2xx responses
    static_configs:
      - targets:
        - http://web:8080  # Internal Docker network URL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
